//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4223
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogheApp.embedded {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BogheApp.embedded.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string AV_ButtonCall {
            get {
                return ResourceManager.GetString("AV_ButtonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Call.
        /// </summary>
        public static string AV_ButtonEndCall {
            get {
                return ResourceManager.GetString("AV_ButtonEndCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Text.
        /// </summary>
        public static string AV_ButtonSendText {
            get {
                return ResourceManager.GetString("AV_ButtonSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add video.
        /// </summary>
        public static string AV_MenuAddVideo {
            get {
                return ResourceManager.GetString("AV_MenuAddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string AV_MenuCall {
            get {
                return ResourceManager.GetString("AV_MenuCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Sharing.
        /// </summary>
        public static string AV_MenuContentSharing {
            get {
                return ResourceManager.GetString("AV_MenuContentSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang Up.
        /// </summary>
        public static string AV_MenuHangUp {
            get {
                return ResourceManager.GetString("AV_MenuHangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Call.
        /// </summary>
        public static string AV_MenuHoldCall {
            get {
                return ResourceManager.GetString("AV_MenuHoldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Audio Call.
        /// </summary>
        public static string AV_MenuMakeAudioCall {
            get {
                return ResourceManager.GetString("AV_MenuMakeAudioCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Transfer.
        /// </summary>
        public static string AV_MenuMakeTransfer {
            get {
                return ResourceManager.GetString("AV_MenuMakeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Video Call.
        /// </summary>
        public static string AV_MenuMakeVideoCall {
            get {
                return ResourceManager.GetString("AV_MenuMakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove video.
        /// </summary>
        public static string AV_MenuRemoveVideo {
            get {
                return ResourceManager.GetString("AV_MenuRemoveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        public static string AV_MenuSendFile {
            get {
                return ResourceManager.GetString("AV_MenuSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Image.
        /// </summary>
        public static string AV_MenuShareImage {
            get {
                return ResourceManager.GetString("AV_MenuShareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        public static string AV_MenuShareVideo {
            get {
                return ResourceManager.GetString("AV_MenuShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start sharing app.
        /// </summary>
        public static string AV_MenuStartSharingApp {
            get {
                return ResourceManager.GetString("AV_MenuStartSharingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop sharing app.
        /// </summary>
        public static string AV_MenuStopSharingApp {
            get {
                return ResourceManager.GetString("AV_MenuStopSharingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name*:.
        /// </summary>
        public static string ContactEdit_DisplayName {
            get {
                return ResourceManager.GetString("ContactEdit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group*:.
        /// </summary>
        public static string ContactEdit_Group {
            get {
                return ResourceManager.GetString("ContactEdit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP URI*:.
        /// </summary>
        public static string ContactEdit_URI {
            get {
                return ResourceManager.GetString("ContactEdit_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name*:.
        /// </summary>
        public static string GroupEdit_DisplayName {
            get {
                return ResourceManager.GetString("GroupEdit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string IM_Abort {
            get {
                return ResourceManager.GetString("IM_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string IM_Invite {
            get {
                return ResourceManager.GetString("IM_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Audio Call.
        /// </summary>
        public static string IM_MakeAudioCall {
            get {
                return ResourceManager.GetString("IM_MakeAudioCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Video Call.
        /// </summary>
        public static string IM_MakeVideoCall {
            get {
                return ResourceManager.GetString("IM_MakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string IM_MenuOptions {
            get {
                return ResourceManager.GetString("IM_MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        public static string IM_SendFile {
            get {
                return ResourceManager.GetString("IM_SendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string IM_Sending {
            get {
                return ResourceManager.GetString("IM_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Text.
        /// </summary>
        public static string IM_SendText {
            get {
                return ResourceManager.GetString("IM_SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Image.
        /// </summary>
        public static string IM_ShareImage {
            get {
                return ResourceManager.GetString("IM_ShareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        public static string IM_ShareVideo {
            get {
                return ResourceManager.GetString("IM_ShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string MainWindow_AddContact {
            get {
                return ResourceManager.GetString("MainWindow_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string MainWindow_AddGroup {
            get {
                return ResourceManager.GetString("MainWindow_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizations (0).
        /// </summary>
        public static string MainWindow_Authorizations {
            get {
                return ResourceManager.GetString("MainWindow_Authorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boghe&apos;s Website.
        /// </summary>
        public static string MainWindow_BogheWebsite {
            get {
                return ResourceManager.GetString("MainWindow_BogheWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainWindow_ButtonCancel {
            get {
                return ResourceManager.GetString("MainWindow_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MainWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("MainWindow_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Events.
        /// </summary>
        public static string MainWindow_DeleteAllEvents {
            get {
                return ResourceManager.GetString("MainWindow_DeleteAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string MainWindow_DeleteContact {
            get {
                return ResourceManager.GetString("MainWindow_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        public static string MainWindow_DeleteGroup {
            get {
                return ResourceManager.GetString("MainWindow_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubango&apos;s Website.
        /// </summary>
        public static string MainWindow_DoubangoWebsite {
            get {
                return ResourceManager.GetString("MainWindow_DoubangoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string MainWindow_EditContact {
            get {
                return ResourceManager.GetString("MainWindow_EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string MainWindow_EditGroup {
            get {
                return ResourceManager.GetString("MainWindow_EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string MainWindow_GettingStarted {
            get {
                return ResourceManager.GetString("MainWindow_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Tracker.
        /// </summary>
        public static string MainWindow_IssueTracker {
            get {
                return ResourceManager.GetString("MainWindow_IssueTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book.
        /// </summary>
        public static string MainWindow_MenuAddressBook {
            get {
                return ResourceManager.GetString("MainWindow_MenuAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuFile {
            get {
                return ResourceManager.GetString("MainWindow_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MainWindow_MenuHistory {
            get {
                return ResourceManager.GetString("MainWindow_MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainWindow_MenuTools {
            get {
                return ResourceManager.GetString("MainWindow_MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have messages.
        /// </summary>
        public static string MainWindow_NoMessages {
            get {
                return ResourceManager.GetString("MainWindow_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainWindow_Options {
            get {
                return ResourceManager.GetString("MainWindow_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainWindow_Refresh {
            get {
                return ResourceManager.GetString("MainWindow_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        public static string MainWindow_Registrations {
            get {
                return ResourceManager.GetString("MainWindow_Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Info.
        /// </summary>
        public static string MainWindow_RequestInfo {
            get {
                return ResourceManager.GetString("MainWindow_RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MainWindow_Reset {
            get {
                return ResourceManager.GetString("MainWindow_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Calls.
        /// </summary>
        public static string MainWindow_ShowCalls {
            get {
                return ResourceManager.GetString("MainWindow_ShowCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Transfers.
        /// </summary>
        public static string MainWindow_ShowFileTransfers {
            get {
                return ResourceManager.GetString("MainWindow_ShowFileTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show History.
        /// </summary>
        public static string MainWindow_ShowHistory {
            get {
                return ResourceManager.GetString("MainWindow_ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Messages.
        /// </summary>
        public static string MainWindow_ShowMessages {
            get {
                return ResourceManager.GetString("MainWindow_ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string MainWindow_SignIn {
            get {
                return ResourceManager.GetString("MainWindow_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string MainWindow_SignOut {
            get {
                return ResourceManager.GetString("MainWindow_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boghe - IMS/RCS Client.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string TabAuthentication {
            get {
                return ResourceManager.GetString("TabAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codecs.
        /// </summary>
        public static string TabCodecs {
            get {
                return ResourceManager.GetString("TabCodecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TabContacts {
            get {
                return ResourceManager.GetString("TabContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URI*:.
        /// </summary>
        public static string TabContacts_BaseURI {
            get {
                return ResourceManager.GetString("TabContacts_BaseURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TabContacts_Password {
            get {
                return ResourceManager.GetString("TabContacts_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Storage.
        /// </summary>
        public static string TabContacts_StorageLocal {
            get {
                return ResourceManager.GetString("TabContacts_StorageLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Storage.
        /// </summary>
        public static string TabContacts_StorageRemote {
            get {
                return ResourceManager.GetString("TabContacts_StorageRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout:.
        /// </summary>
        public static string TabContacts_Timeout {
            get {
                return ResourceManager.GetString("TabContacts_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Video Call.
        /// </summary>
        public static string TabContacts_ToolTipMakeVideoCall {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipMakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Voice Call.
        /// </summary>
        public static string TabContacts_ToolTipMakeVoiceCall {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipMakeVoiceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        public static string TabContacts_ToolTipSendFile {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Chat.
        /// </summary>
        public static string TabContacts_ToolTipStartChat {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipStartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username*:.
        /// </summary>
        public static string TabContacts_Username {
            get {
                return ResourceManager.GetString("TabContacts_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCAP Preferences.
        /// </summary>
        public static string TabContacts_XCAPPrefs {
            get {
                return ResourceManager.GetString("TabContacts_XCAPPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENUM (E.164) domain.
        /// </summary>
        public static string TabGeneral_Enum {
            get {
                return ResourceManager.GetString("TabGeneral_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch when system starts.
        /// </summary>
        public static string TabGeneral_LaunchWhenStart {
            get {
                return ResourceManager.GetString("TabGeneral_LaunchWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Profile.
        /// </summary>
        public static string TabGeneral_Profile {
            get {
                return ResourceManager.GetString("TabGeneral_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string TabHistory {
            get {
                return ResourceManager.GetString("TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string TabIdentity {
            get {
                return ResourceManager.GetString("TabIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMF*:.
        /// </summary>
        public static string TabIdentity_AMF {
            get {
                return ResourceManager.GetString("TabIdentity_AMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string TabIdentity_ConSettings {
            get {
                return ResourceManager.GetString("TabIdentity_ConSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName*:.
        /// </summary>
        public static string TabIdentity_DisplayName {
            get {
                return ResourceManager.GetString("TabIdentity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 3GPP Early IMS Security.
        /// </summary>
        public static string TabIdentity_EnableEarlyIMS {
            get {
                return ResourceManager.GetString("TabIdentity_EnableEarlyIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ID*:.
        /// </summary>
        public static string TabIdentity_OpId {
            get {
                return ResourceManager.GetString("TabIdentity_OpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password*:.
        /// </summary>
        public static string TabIdentity_Password {
            get {
                return ResourceManager.GetString("TabIdentity_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy:.
        /// </summary>
        public static string TabIdentity_Privacy {
            get {
                return ResourceManager.GetString("TabIdentity_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Identity*:.
        /// </summary>
        public static string TabIdentity_PrivateId {
            get {
                return ResourceManager.GetString("TabIdentity_PrivateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Identity*:.
        /// </summary>
        public static string TabIdentity_PublicId {
            get {
                return ResourceManager.GetString("TabIdentity_PublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm*:.
        /// </summary>
        public static string TabIdentity_Realm {
            get {
                return ResourceManager.GetString("TabIdentity_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TabIdentity_Security {
            get {
                return ResourceManager.GetString("TabIdentity_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string TabMessaging {
            get {
                return ResourceManager.GetString("TabMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Encoding (3GPP SMSIP).
        /// </summary>
        public static string TabMessaging_Binary {
            get {
                return ResourceManager.GetString("TabMessaging_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string TabMessaging_Chat {
            get {
                return ResourceManager.GetString("TabMessaging_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Instant Message Disposition Notification (IMDN).
        /// </summary>
        public static string TabMessaging_EnableIMDN {
            get {
                return ResourceManager.GetString("TabMessaging_EnableIMDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Indication of Message Composition for Instant Messaging.
        /// </summary>
        public static string TabMessaging_EnableIsComposing {
            get {
                return ResourceManager.GetString("TabMessaging_EnableIsComposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MSRP Failure Reports.
        /// </summary>
        public static string TabMessaging_EnableMSRPFailureReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableMSRPFailureReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MSRP Success Reports.
        /// </summary>
        public static string TabMessaging_EnableMSRPSuccessReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableMSRPSuccessReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable OMA Final Delivery Reports.
        /// </summary>
        public static string TabMessaging_EnableOMAFinalDeliveryReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableOMAFinalDeliveryReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text Encoding.
        /// </summary>
        public static string TabMessaging_PlainText {
            get {
                return ResourceManager.GetString("TabMessaging_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string TabMessaging_SMS {
            get {
                return ResourceManager.GetString("TabMessaging_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Center.
        /// </summary>
        public static string TabMessaging_SMSC {
            get {
                return ResourceManager.GetString("TabMessaging_SMSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATT.
        /// </summary>
        public static string TabNATT {
            get {
                return ResourceManager.GetString("TabNATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover STUN/TURN server.
        /// </summary>
        public static string TabNATT_Discover_STUNSrv {
            get {
                return ResourceManager.GetString("TabNATT_Discover_STUNSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable STUN for ICE.
        /// </summary>
        public static string TabNATT_EnableSTUNForICE {
            get {
                return ResourceManager.GetString("TabNATT_EnableSTUNForICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable STUN for SIP.
        /// </summary>
        public static string TabNATT_EnableSTUNForSIP {
            get {
                return ResourceManager.GetString("TabNATT_EnableSTUNForSIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TURN for ICE.
        /// </summary>
        public static string TabNATT_EnableTURNForICE {
            get {
                return ResourceManager.GetString("TabNATT_EnableTURNForICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string TabNATT_Port {
            get {
                return ResourceManager.GetString("TabNATT_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string TabNATT_Server {
            get {
                return ResourceManager.GetString("TabNATT_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUN / TURN.
        /// </summary>
        public static string TabNATT_STUNTURN {
            get {
                return ResourceManager.GetString("TabNATT_STUNTURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT Traversal.
        /// </summary>
        public static string TabNATT_Title {
            get {
                return ResourceManager.GetString("TabNATT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this STUN/TURN server.
        /// </summary>
        public static string TabNATT_UseSTUNSrv {
            get {
                return ResourceManager.GetString("TabNATT_UseSTUNSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string TabNetwork {
            get {
                return ResourceManager.GetString("TabNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Type.
        /// </summary>
        public static string TabNetwork_AccessType {
            get {
                return ResourceManager.GetString("TabNetwork_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-CSCF discovery using DHCP.
        /// </summary>
        public static string TabNetwork_DiscoDHCP {
            get {
                return ResourceManager.GetString("TabNetwork_DiscoDHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-CSCF discovery using DNS NAPTR + SRV.
        /// </summary>
        public static string TabNetwork_DiscoDNS {
            get {
                return ResourceManager.GetString("TabNetwork_DiscoDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Signaling Compression (SigComp).
        /// </summary>
        public static string TabNetwork_EnableSigComp {
            get {
                return ResourceManager.GetString("TabNetwork_EnableSigComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        public static string TabNetwork_Info {
            get {
                return ResourceManager.GetString("TabNetwork_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Version.
        /// </summary>
        public static string TabNetwork_IPVersion {
            get {
                return ResourceManager.GetString("TabNetwork_IPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string TabNetwork_Network {
            get {
                return ResourceManager.GetString("TabNetwork_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-CSCF Host*:.
        /// </summary>
        public static string TabNetwork_ProxyHost {
            get {
                return ResourceManager.GetString("TabNetwork_ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-CSCF port*:.
        /// </summary>
        public static string TabNetwork_ProxyPort {
            get {
                return ResourceManager.GetString("TabNetwork_ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabNetwork_Settings {
            get {
                return ResourceManager.GetString("TabNetwork_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string TabNetwork_Title {
            get {
                return ResourceManager.GetString("TabNetwork_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport*:.
        /// </summary>
        public static string TabNetwork_Transport {
            get {
                return ResourceManager.GetString("TabNetwork_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string TabPresence {
            get {
                return ResourceManager.GetString("TabPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Size MUST be at least 80x60 or 60x80 and ratio must be 4/3.
        /// </summary>
        public static string TabPresence_AvatarSize {
            get {
                return ResourceManager.GetString("TabPresence_AvatarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Publication.
        /// </summary>
        public static string TabPresence_EnablePublication {
            get {
                return ResourceManager.GetString("TabPresence_EnablePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RLS when XCAP is enabled.
        /// </summary>
        public static string TabPresence_EnableRLS {
            get {
                return ResourceManager.GetString("TabPresence_EnableRLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Subscription.
        /// </summary>
        public static string TabPresence_EnableSubscription {
            get {
                return ResourceManager.GetString("TabPresence_EnableSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Text.
        /// </summary>
        public static string TabPresence_FreeText {
            get {
                return ResourceManager.GetString("TabPresence_FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TabPresence_HomePage {
            get {
                return ResourceManager.GetString("TabPresence_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-Availability Timeout.
        /// </summary>
        public static string TabPresence_HyperAvailTimeout {
            get {
                return ResourceManager.GetString("TabPresence_HyperAvailTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string TabPresence_Minutes {
            get {
                return ResourceManager.GetString("TabPresence_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string TabPresence_Publication {
            get {
                return ResourceManager.GetString("TabPresence_Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Icon (Click on the box to change).
        /// </summary>
        public static string TabPresence_StatusIcon {
            get {
                return ResourceManager.GetString("TabPresence_StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string TabPresence_Subscription {
            get {
                return ResourceManager.GetString("TabPresence_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QoS/QoE.
        /// </summary>
        public static string TabQoS {
            get {
                return ResourceManager.GetString("TabQoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth:.
        /// </summary>
        public static string TabQoS_Bandwidth {
            get {
                return ResourceManager.GetString("TabQoS_Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Session Timers.
        /// </summary>
        public static string TabQoS_EnableSessionTimers {
            get {
                return ResourceManager.GetString("TabQoS_EnableSessionTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TabQoS_General {
            get {
                return ResourceManager.GetString("TabQoS_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preconditions.
        /// </summary>
        public static string TabQoS_Preconditions {
            get {
                return ResourceManager.GetString("TabQoS_Preconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred video Size:.
        /// </summary>
        public static string TabQoS_PrefVideoSize {
            get {
                return ResourceManager.GetString("TabQoS_PrefVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresher:.
        /// </summary>
        public static string TabQoS_Refresher {
            get {
                return ResourceManager.GetString("TabQoS_Refresher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timers.
        /// </summary>
        public static string TabQoS_SessionTimers {
            get {
                return ResourceManager.GetString("TabQoS_SessionTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string TabQoS_Strength {
            get {
                return ResourceManager.GetString("TabQoS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout:.
        /// </summary>
        public static string TabQoS_Timeout {
            get {
                return ResourceManager.GetString("TabQoS_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QoS/QoE.
        /// </summary>
        public static string TabQoS_Title {
            get {
                return ResourceManager.GetString("TabQoS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TabQoS_Type {
            get {
                return ResourceManager.GetString("TabQoS_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Video Artifacts (Perfect Quality).
        /// </summary>
        public static string TabQoS_ZeroVideoArtifacts {
            get {
                return ResourceManager.GetString("TabQoS_ZeroVideoArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TabSecurity {
            get {
                return ResourceManager.GetString("TabSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm:.
        /// </summary>
        public static string TabSecurity_Algorithm {
            get {
                return ResourceManager.GetString("TabSecurity_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File:.
        /// </summary>
        public static string TabSecurity_CertFile {
            get {
                return ResourceManager.GetString("TabSecurity_CertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Algorithm:.
        /// </summary>
        public static string TabSecurity_EAlgorithm {
            get {
                return ResourceManager.GetString("TabSecurity_EAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable IPSec.
        /// </summary>
        public static string TabSecurity_EnableIPSec {
            get {
                return ResourceManager.GetString("TabSecurity_EnableIPSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPSec Parameters.
        /// </summary>
        public static string TabSecurity_IPSecParams {
            get {
                return ResourceManager.GetString("TabSecurity_IPSecParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string TabSecurity_Mode {
            get {
                return ResourceManager.GetString("TabSecurity_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private File:.
        /// </summary>
        public static string TabSecurity_PrivateFile {
            get {
                return ResourceManager.GetString("TabSecurity_PrivateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        public static string TabSecurity_Protocol {
            get {
                return ResourceManager.GetString("TabSecurity_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public File.
        /// </summary>
        public static string TabSecurity_PublicFile {
            get {
                return ResourceManager.GetString("TabSecurity_PublicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRTP Parameters.
        /// </summary>
        public static string TabSecurity_SRTPParams {
            get {
                return ResourceManager.GetString("TabSecurity_SRTPParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS Parameters.
        /// </summary>
        public static string TabSecurity_TLSParams {
            get {
                return ResourceManager.GetString("TabSecurity_TLSParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TabSecurity_Type {
            get {
                return ResourceManager.GetString("TabSecurity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Text_Accepted {
            get {
                return ResourceManager.GetString("Text_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string Text_AddContact {
            get {
                return ResourceManager.GetString("Text_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Text_Answer {
            get {
                return ResourceManager.GetString("Text_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Text_Call {
            get {
                return ResourceManager.GetString("Text_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call in progress.
        /// </summary>
        public static string Text_CallInProgress {
            get {
                return ResourceManager.GetString("Text_CallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call placed on hold.
        /// </summary>
        public static string Text_CallPlacedOnHold {
            get {
                return ResourceManager.GetString("Text_CallPlacedOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call taken off hold.
        /// </summary>
        public static string Text_CallTakenOffHold {
            get {
                return ResourceManager.GetString("Text_CallTakenOffHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Terminated.
        /// </summary>
        public static string Text_CallTerminated {
            get {
                return ResourceManager.GetString("Text_CallTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Transfer.
        /// </summary>
        public static string Text_CallTransfer {
            get {
                return ResourceManager.GetString("Text_CallTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Text_Completed {
            get {
                return ResourceManager.GetString("Text_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Media Started.
        /// </summary>
        public static string Text_EarlyMediaStarted {
            get {
                return ResourceManager.GetString("Text_EarlyMediaStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string Text_EditContact {
            get {
                return ResourceManager.GetString("Text_EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Text_Failed {
            get {
                return ResourceManager.GetString("Text_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place remote party on hold.
        /// </summary>
        public static string Text_FailedToPlaceRemotePartyOnHold {
            get {
                return ResourceManager.GetString("Text_FailedToPlaceRemotePartyOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unhold call.
        /// </summary>
        public static string Text_FailedToUnholdCall {
            get {
                return ResourceManager.GetString("Text_FailedToUnholdCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Call.
        /// </summary>
        public static string Text_HoldCall {
            get {
                return ResourceManager.GetString("Text_HoldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Call.
        /// </summary>
        public static string Text_InCall {
            get {
                return ResourceManager.GetString("Text_InCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call from.
        /// </summary>
        public static string Text_IncomingCall {
            get {
                return ResourceManager.GetString("Text_IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiated.
        /// </summary>
        public static string Text_Initiated {
            get {
                return ResourceManager.GetString("Text_Initiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed on hold by remote party.
        /// </summary>
        public static string Text_PlacedOnHoldByRemoteParty {
            get {
                return ResourceManager.GetString("Text_PlacedOnHoldByRemoteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResumeCall.
        /// </summary>
        public static string Text_ResumeCall {
            get {
                return ResourceManager.GetString("Text_ResumeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing.
        /// </summary>
        public static string Text_Ringing {
            get {
                return ResourceManager.GetString("Text_Ringing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string Text_SendSMS {
            get {
                return ResourceManager.GetString("Text_SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Text.
        /// </summary>
        public static string Text_SendText {
            get {
                return ResourceManager.GetString("Text_SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken off hold by remote party.
        /// </summary>
        public static string Text_TakenOffHoldByRemoteParty {
            get {
                return ResourceManager.GetString("Text_TakenOffHoldByRemoteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talking with.
        /// </summary>
        public static string Text_TalkingWith {
            get {
                return ResourceManager.GetString("Text_TalkingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Text_Transfer {
            get {
                return ResourceManager.GetString("Text_Transfer", resourceCulture);
            }
        }
    }
}
