//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogheApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BogheApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap avatar_48 {
            get {
                object obj = ResourceManager.GetObject("avatar_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_blue_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_blue_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_green_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_green_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_grey_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_grey_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_red_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_red_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_yellow_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_yellow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_incoming_45 {
            get {
                object obj = ResourceManager.GetObject("call_incoming_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_missed_45 {
            get {
                object obj = ResourceManager.GetObject("call_missed_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_outgoing_45 {
            get {
                object obj = ResourceManager.GetObject("call_outgoing_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_0 {
            get {
                return ResourceManager.GetStream("dtmf_0", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_1 {
            get {
                return ResourceManager.GetStream("dtmf_1", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_2 {
            get {
                return ResourceManager.GetStream("dtmf_2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_3 {
            get {
                return ResourceManager.GetStream("dtmf_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_4 {
            get {
                return ResourceManager.GetStream("dtmf_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_5 {
            get {
                return ResourceManager.GetStream("dtmf_5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_6 {
            get {
                return ResourceManager.GetStream("dtmf_6", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_7 {
            get {
                return ResourceManager.GetStream("dtmf_7", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_8 {
            get {
                return ResourceManager.GetStream("dtmf_8", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_9 {
            get {
                return ResourceManager.GetStream("dtmf_9", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_pound {
            get {
                return ResourceManager.GetStream("dtmf_pound", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_star {
            get {
                return ResourceManager.GetStream("dtmf_star", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap gsma_rcs {
            get {
                object obj = ResourceManager.GetObject("gsma_rcs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hourglass_24 {
            get {
                object obj = ResourceManager.GetObject("hourglass_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16 {
            get {
                object obj = ResourceManager.GetObject("icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_16 {
            get {
                object obj = ResourceManager.GetObject("lock_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_24 {
            get {
                object obj = ResourceManager.GetObject("lock_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_32 {
            get {
                object obj = ResourceManager.GetObject("lock_error_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_16 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_24 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_32 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_open_24 {
            get {
                object obj = ResourceManager.GetObject("lock_open_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_16 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_24 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_32 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] log4net_xml {
            get {
                object obj = ResourceManager.GetObject("log4net_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream newevent {
            get {
                return ResourceManager.GetStream("newevent", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream ringbacktone {
            get {
                return ResourceManager.GetStream("ringbacktone", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream ringtone {
            get {
                return ResourceManager.GetStream("ringtone", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap signin_16 {
            get {
                object obj = ResourceManager.GetObject("signin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap signin_161 {
            get {
                object obj = ResourceManager.GetObject("signin_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap signout_16 {
            get {
                object obj = ResourceManager.GetObject("signout_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_16 {
            get {
                object obj = ResourceManager.GetObject("user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_back16 {
            get {
                object obj = ResourceManager.GetObject("user_back16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_busy_16 {
            get {
                object obj = ResourceManager.GetObject("user_busy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_hyper_avail_16 {
            get {
                object obj = ResourceManager.GetObject("user_hyper_avail_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_offline_16 {
            get {
                object obj = ResourceManager.GetObject("user_offline_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_onthephone_16 {
            get {
                object obj = ResourceManager.GetObject("user_onthephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_time_16 {
            get {
                object obj = ResourceManager.GetObject("user_time_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
