//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4223
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogheApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BogheApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap avatar_48 {
            get {
                object obj = ResourceManager.GetObject("avatar_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_blue_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_blue_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_blue_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_green_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_green_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_green_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_grey_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_grey_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_grey_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_grey_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_red_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_red_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_red_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_yellow_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_yellow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bullet_ball_glass_yellow_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_yellow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_hold_16 {
            get {
                object obj = ResourceManager.GetObject("call_hold_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_incoming_45 {
            get {
                object obj = ResourceManager.GetObject("call_incoming_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_missed_45 {
            get {
                object obj = ResourceManager.GetObject("call_missed_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_outgoing_45 {
            get {
                object obj = ResourceManager.GetObject("call_outgoing_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap call_resume_16 {
            get {
                object obj = ResourceManager.GetObject("call_resume_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clear_16 {
            get {
                object obj = ResourceManager.GetObject("clear_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream connevent {
            get {
                return ResourceManager.GetStream("connevent", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap document_down_16 {
            get {
                object obj = ResourceManager.GetObject("document_down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_down_32 {
            get {
                object obj = ResourceManager.GetObject("document_down_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_forbidden_16 {
            get {
                object obj = ResourceManager.GetObject("document_forbidden_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_forbidden_32 {
            get {
                object obj = ResourceManager.GetObject("document_forbidden_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_up_16 {
            get {
                object obj = ResourceManager.GetObject("document_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap document_up_32 {
            get {
                object obj = ResourceManager.GetObject("document_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_0 {
            get {
                return ResourceManager.GetStream("dtmf_0", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_1 {
            get {
                return ResourceManager.GetStream("dtmf_1", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_2 {
            get {
                return ResourceManager.GetStream("dtmf_2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_3 {
            get {
                return ResourceManager.GetStream("dtmf_3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_4 {
            get {
                return ResourceManager.GetStream("dtmf_4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_5 {
            get {
                return ResourceManager.GetStream("dtmf_5", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_6 {
            get {
                return ResourceManager.GetStream("dtmf_6", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_7 {
            get {
                return ResourceManager.GetStream("dtmf_7", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_8 {
            get {
                return ResourceManager.GetStream("dtmf_8", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_9 {
            get {
                return ResourceManager.GetStream("dtmf_9", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_pound {
            get {
                return ResourceManager.GetStream("dtmf_pound", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dtmf_star {
            get {
                return ResourceManager.GetStream("dtmf_star", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap gsma_rcs {
            get {
                object obj = ResourceManager.GetObject("gsma_rcs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hourglass_24 {
            get {
                object obj = ResourceManager.GetObject("hourglass_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16 {
            get {
                object obj = ResourceManager.GetObject("icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon icon_message_16 {
            get {
                object obj = ResourceManager.GetObject("icon_message_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon icon_messages_16 {
            get {
                object obj = ResourceManager.GetObject("icon_messages_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap key_ok_24 {
            get {
                object obj = ResourceManager.GetObject("key_ok_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_16 {
            get {
                object obj = ResourceManager.GetObject("lock_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_24 {
            get {
                object obj = ResourceManager.GetObject("lock_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_error_32 {
            get {
                object obj = ResourceManager.GetObject("lock_error_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_16 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_24 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_ok_32 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_open_24 {
            get {
                object obj = ResourceManager.GetObject("lock_open_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_16 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_24 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lock_warning_32 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;log4net&gt;
        ///  
        ///  &lt;appender name=&quot;ConsoleAppender&quot; type=&quot;log4net.Appender.ConsoleAppender&quot;&gt;
        ///    &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///      &lt;conversionPattern value=&quot;%date %-5level [%thread] %logger:%line - %message%newline&quot;/&gt;
        ///    &lt;/layout&gt;
        ///  &lt;/appender&gt;
        ///
        ///  &lt;appender name=&quot;FileAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///    &lt;file value=&quot;{0}\Boghe.log&quot;/&gt;
        ///    &lt;appendToFile value=&quot;true&quot;/&gt;
        ///    &lt;rollingStyle value=&quot;Date&quot;/&gt;
        ///    &lt;datePattern value [rest of string was truncated]&quot;;.
        /// </summary>
        public static string log4net_xml {
            get {
                return ResourceManager.GetString("log4net_xml", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap message_16 {
            get {
                object obj = ResourceManager.GetObject("message_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap message_24 {
            get {
                object obj = ResourceManager.GetObject("message_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap messages_16 {
            get {
                object obj = ResourceManager.GetObject("messages_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap messages_24 {
            get {
                object obj = ResourceManager.GetObject("messages_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap messages_32 {
            get {
                object obj = ResourceManager.GetObject("messages_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream newsms {
            get {
                return ResourceManager.GetStream("newsms", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap phone_hang_up_32 {
            get {
                object obj = ResourceManager.GetObject("phone_hang_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap phone_pick_up_32 {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream ringbacktone {
            get {
                return ResourceManager.GetStream("ringbacktone", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream ringtone {
            get {
                return ResourceManager.GetStream("ringtone", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap secure_16 {
            get {
                object obj = ResourceManager.GetObject("secure_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap signin_16 {
            get {
                object obj = ResourceManager.GetObject("signin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap signin_161 {
            get {
                object obj = ResourceManager.GetObject("signin_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap signout_16 {
            get {
                object obj = ResourceManager.GetObject("signout_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sound_off_16 {
            get {
                object obj = ResourceManager.GetObject("sound_off_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sound_off_32 {
            get {
                object obj = ResourceManager.GetObject("sound_off_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sound_on_16 {
            get {
                object obj = ResourceManager.GetObject("sound_on_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sound_on_32 {
            get {
                object obj = ResourceManager.GetObject("sound_on_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Strings_fr_FR {
            get {
                return ResourceManager.GetString("Strings_fr_FR", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap user_16 {
            get {
                object obj = ResourceManager.GetObject("user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_back16 {
            get {
                object obj = ResourceManager.GetObject("user_back16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_busy_16 {
            get {
                object obj = ResourceManager.GetObject("user_busy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_hyper_avail_16 {
            get {
                object obj = ResourceManager.GetObject("user_hyper_avail_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_mobilephone_32 {
            get {
                object obj = ResourceManager.GetObject("user_mobilephone_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_offline_16 {
            get {
                object obj = ResourceManager.GetObject("user_offline_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_onthephone_16 {
            get {
                object obj = ResourceManager.GetObject("user_onthephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_time_16 {
            get {
                object obj = ResourceManager.GetObject("user_time_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap video_pause_16 {
            get {
                object obj = ResourceManager.GetObject("video_pause_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap video_play_16 {
            get {
                object obj = ResourceManager.GetObject("video_play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
